(ns euler.twelve
  (:require [clojure.edn :as edn])
  (:require [clojure.math.numeric-tower :as math]))

;; Problem 12
;; ==========

;;    The sequence of triangle numbers is generated by adding the natural
;;    numbers. So the 7^th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
;;    28. The first ten terms would be:

;;                     1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

;;    Let us list the factors of the first seven triangle numbers:

;;       1: 1
;;       3: 1,3
;;       6: 1,2,3,6
;;      10: 1,2,5,10
;;      15: 1,3,5,15
;;      21: 1,3,7,21
;;      28: 1,2,4,7,14,28

;;    We can see that 28 is the first triangle number to have over five
;;    divisors.

;;    What is the value of the first triangle number to have over five hundred
;;    divisors?

   
;;    Answer: 8091de7d285989bbfa9a2f9f3bdcc7c0

(defn gcd [x y]
  (cond
    (> x y)
    (gcd (- x y) y)
    (< x y)
    (gcd x (- y x))
    :else x))
 
(defn t [n]
  (reduce + (range 1 n)))

(memoize t)
(let [[a b] (drop 998 (take 1000 (pmap t (range 2 10000))))]
   (gcd a b))


