(ns logic
  (:require
   [clojure.core.logic :refer :all]
   [clojure.core.logic.fd :as fd]
   [clojure.math.numeric-tower :as math]
   [clojure.core.match :refer [match]]))


;; Prolog has | for head tail seperator matching
;; Clojure has defne I think

;; all factors of 36 below 11
(run* [q r]
  (fd/in q r (fd/interval 0 11))
  (fd/* q r 36)) 
;; => ([4 9] [6 6] [9 4])



;; all factors of 36 below 11
(run* [q r]
  (fresh [a b i j]
    (fd/in a b i j (fd/interval 1 30))
    (fd/* 5 a b)
    (fd/* 3 i j)
    (!= [a b] q)
    (!= [i j] r)))

(run 30 [q]
  (fresh [r t f]
    (fd/in r t f (fd/interval 11))
    (fd/+ r 3 t)
    (fd/+ t 4 f)
    (fd/+ r 7 f)
    (== q [r t f])))


(run 90 [q]
  (fresh [do re mi so fa la ti]
    (== q [do re mi so fa la ti])
    (fd/in do re mi so fa la ti (fd/interval 0 127))
    (fd/+ do 2 re)
    (fd/+ re 2 mi)
    (fd/+ mi 3 so)
    (fd/+ so 2 fa)
    (fd/+ fa 2 la)
    (fd/+ la 3 ti)

    (fd/< do re)
    (fd/< re mi)
    (fd/< mi so)
    (fd/< so fa)
    (fd/< fa la)
    (fd/< la ti)

    (distincto q)
    ))


(def euler-problems (clojure.string/split (slurp "resources/euler_problems.txt")
                                          #"\#\#\#\#"))

(run* [q]
  (or*
   [(== 1 q)
    (== 0 q)])) ;; 🅱OOLE IN IT

(run* [q]
  (fresh [a b c]
    (fd/in q a b (fd/interval 1 9))
    (or* [(== b 5)
          (== a 3)])
    (fd/* a b q)))
;; => (5 3 6 9)



(def below-thou
  (into #{}
        (run* [q]
          (fresh [a b c]
            (fd/in q a b (fd/interval 1 999))
            (or* [(== b 5)
                  (== a 3)])
            (fd/* a b q)))))

(reduce + 0
        (for [x (range 1 1000)
              :when (or (zero? (mod x 5))
                        (zero? (mod x 3)))]
          x))


(reduce + 0 below-thou)



(nth euler-problems 1)
;; => "\nProblem 2\n=========\n\n\n   Each new term in the Fibonacci sequence is generated by adding the\n   previous two terms. By starting with 1 and 2, the first 10 terms will be:\n\n                     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\n   By considering the terms in the Fibonacci sequence whose values do not\n   exceed four million, find the sum of the even-valued terms.\n\n   \n   Answer: 4194eb91842c8e7e6df099ca73c38f28\n\n\n\n"


(defn fibo [n]
  (if (< n 2)
    n

    (+ (fibo (dec n)) (fibo (dec (dec n))))))

(defn fibo [n]
  (cond (< n 2) n
        :else
        (+ (fibo (dec n)) (fibo (dec (dec n))))))


(defn fiboo [n]
  (conde
   [(< n 2) n
    s# (+ (fiboo (dec n)) (fiboo (dec (dec n))))]))



(run* [q]
  (fiboo q))

(fibo 40)

(run* [q]
  (fresh [f0 f1]
    (fd/in f0 f1 (fd/interval 10))
    (fd/+ f0 f1 q)))


;; https://www.youtube.com/watch?v=7kPMFkNm2dw
